const fs = require("fs");

const lines = [
  "const STACK_KEYWORDS: string[] = [",
  '  "react", "vue", "angular", "svelte", "next.js", "nuxt", "typescript", "javascript",',
  '  "html", "css", "sass", "scss", "webpack", "vite", "rollup", "babel",',
  '  "redux", "mobx", "zustand", "graphql", "apollo", "tailwind", "bootstrap",',
  '  "styled-components", "jest", "cypress", "playwright", "storybook",',
  '  "node.js", "express", "nestjs", "fastify", "koa",',
  '  "python", "django", "flask", "fastapi",',
  '  "golang", "gin", "echo", "fiber",',
  '  "java", "spring", "php", "laravel", "symfony", "ruby", "rails", "rust",',
  '  "c#", ".net", "postgresql", "postgres", "mysql", "mariadb", "sqlite",',
  '  "mongodb", "redis", "elasticsearch", "clickhouse",',
  '  "docker", "kubernetes", "k8s", "terraform", "aws", "gcp", "azure", "linux", "nginx",',
  '  "react native", "flutter", "swift", "kotlin",',
  "];",
  "",
  "/**",
  " * Извлекает список технологий из произвольного набора текстов.",
  " */",
  "export function extractStack(...texts: string[]): string[] {",
  '  const combined = texts.join(" ").toLowerCase();',
  "  const found: string[] = [];",
  "  for (const kw of STACK_KEYWORDS) {",
  '    const escaped = kw.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");',
  '    const re = new RegExp("(?<![a-z0-9])" + escaped + "(?![a-z0-9])", "i");',
  "    if (re.test(combined)) found.push(kw);",
  "  }",
  "  return found;",
  "}",
  "",
  "/**",
  " * Парсит строку зарплаты и возвращает читаемую строку или null.",
  " */",
  "export function parseSalary(raw: string | null | undefined): string | null {",
  "  if (!raw) return null;",
  '  const text = raw.replace(/\\s+/g, " ").trim();',
  "  const rangeMatch = /([\\d\\s]{2,})\\s*[-\\u2013]\\s*([\\d\\s]{2,})/i.exec(text);",
  "  const singleMatch = /(\\d{3,}[\\d\\s]*)/i.exec(text);",
  "  const currencyMatch = /(usd|eur|byn|rub|rur|kzt|amd|gel)/i.exec(text);",
  '  const cur = currencyMatch?.[1]?.toUpperCase() ?? "";',
  "  if (rangeMatch) {",
  '    const from = (rangeMatch[1] ?? "").replace(/\\s/g, "");',
  '    const to = (rangeMatch[2] ?? "").replace(/\\s/g, "");',
  '    return (from + "-" + to + (cur ? " " + cur : "")).trim() || null;',
  "  }",
  "  if (singleMatch) {",
  '    const val = (singleMatch[1] ?? "").replace(/\\s/g, "");',
  '    return (val + (cur ? " " + cur : "")).trim() || null;',
  "  }",
  "  return null;",
  "}",
];

fs.writeFileSync("src/utils.ts", lines.join("\n"), "utf8");
console.log("Written", lines.length, "lines to src/utils.ts");
