const fs = require("node:fs");

const lines = [
  'import axios from "axios";',
  'import { ParsedVacancy, Country, JobCategory, Source } from "../types";',
  'import logger from "../logger";',
  'import { config } from "../config";',
  'import { extractStack } from "../utils";',
  'import { sleep, detectWorkFormat, detectCategory } from "../scraper-utils";',
  "",
  "// --- Constants ---",
  "",
  'const HH_BASE = "https://api.hh.ru";',
  "",
  "const COUNTRY_AREA: Record<Country, string> = {",
  '  RU: "113",',
  '  BY: "16",',
  '  KZ: "40",',
  '  AM: "1012",',
  '  GE: "28",',
  "};",
  "",
  "const SEARCH_QUERIES: Record<JobCategory, string[]> = {",
  "  frontend: [",
  '    "frontend разработчик",',
  '    "react разработчик",',
  '    "vue разработчик",',
  '    "svelte разработчик",',
  "  ],",
  "  backend: [",
  '    "backend разработчик",',
  '    "python разработчик",',
  '    "golang разработчик",',
  '    "php разработчик",',
  "  ],",
  '  fullstack: ["fullstack разработчик"],',
  "};",
  "",
  "const CURRENCY_SYMBOL: Record<string, string> = {",
  '  RUR: "\\u20BD", RUB: "\\u20BD", USD: "$", EUR: "\\u20AC",',
  '  KZT: "\\u20B8", GEL: "\\u20BE", AMD: "\\u058F", BYR: "Br", BYN: "Br",',
  "};",
  "",
  "// --- HH API Types ---",
  "",
  "interface HHSalary { from: number | null; to: number | null; currency: string }",
  "interface HHVacancy {",
  "  id: string;",
  "  name: string;",
  "  employer: { name: string };",
  "  salary: HHSalary | null;",
  "  snippet: { requirement: string | null };",
  "  schedule: { id: string };",
  "  area: { name: string };",
  "  alternate_url: string;",
  "  published_at: string;",
  "}",
  "interface HHResponse { items: HHVacancy[]; found: number }",
  "",
  "// --- OAuth Cache ---",
  "",
  "interface TokenCache { token: string; expiresAt: number }",
  "let tokenCache: TokenCache | null = null;",
  "",
  "async function getAccessToken(): Promise<string | null> {",
  "  const { apiToken, clientId, clientSecret } = config.hh;",
  "  if (apiToken) return apiToken;",
  "  if (!clientId || !clientSecret) return null;",
  "  if (tokenCache && tokenCache.expiresAt > Date.now() + 60_000) return tokenCache.token;",
  "  try {",
  '    logger.info("[HH] Получаем OAuth токен...");',
  "    const { data } = await axios.post<{ access_token: string; expires_in: number }>(",
  '      "https://hh.ru/oauth/token",',
  '      new URLSearchParams({ grant_type: "client_credentials", client_id: clientId, client_secret: clientSecret }),',
  '      { headers: { "Content-Type": "application/x-www-form-urlencoded" } },',
  "    );",
  "    tokenCache = { token: data.access_token, expiresAt: Date.now() + data.expires_in * 1_000 };",
  '    logger.info("[HH] OAuth токен получен");',
  "    return tokenCache.token;",
  "  } catch (err) {",
  '    logger.error("[HH] Ошибка получения OAuth токена: " + String(err));',
  "    return null;",
  "  }",
  "}",
  "",
  "// --- Formatting ---",
  "",
  "function formatSalary(s: HHSalary | null): string | null {",
  "  if (!s) return null;",
  "  const cur = CURRENCY_SYMBOL[s.currency] ?? s.currency;",
  '  if (s.from && s.to) return s.from + "\\u2013" + s.to + " " + cur;',
  '  if (s.from) return "от " + s.from + " " + cur;',
  '  if (s.to) return "до " + s.to + " " + cur;',
  "  return null;",
  "}",
  "",
  "// --- API Requests ---",
  "",
  "async function fetchVacancies(",
  "  query: string, category: JobCategory, country: Country,",
  "  areaId: string, headers: Record<string, string>, maxPerRun: number,",
  "): Promise<ParsedVacancy[]> {",
  '  const { data } = await axios.get<HHResponse>(HH_BASE + "/vacancies", {',
  "    headers,",
  '    params: { text: query, area: areaId, per_page: maxPerRun, page: 0, order_by: "publication_time" },',
  "  });",
  '  logger.info("[HH] " + category + "/" + country + " \\"" + query + "\\": всего " + data.found + ", получено " + data.items.length);',
  "  return data.items.map((item) => ({",
  '    sourceId: "hh_" + item.id,',
  "    title: item.name,",
  "    company: item.employer.name,",
  "    salary: formatSalary(item.salary),",
  '    stack: extractStack(item.name, item.snippet?.requirement ?? ""),',
  '    workFormat: detectWorkFormat(item.name + " " + (item.schedule?.id ?? "")),',
  "    country,",
  "    city: item.area?.name ?? null,",
  "    url: item.alternate_url,",
  '    source: "hh.ru",',
  "    category: detectCategory(item.name) ?? category,",
  "    publishedAt: new Date(item.published_at),",
  "  }));",
  "}",
  "",
  "async function scrapeQuery(",
  "  query: string, cat: JobCategory, country: Country,",
  "  areaId: string, headers: Record<string, string>,",
  "  seenIds: Set<string>, out: ParsedVacancy[],",
  "): Promise<boolean> {",
  "  try {",
  "    const chunk = await fetchVacancies(query, cat, country, areaId, headers, config.bot.maxVacanciesPerRun);",
  "    for (const v of chunk) {",
  "      if (!seenIds.has(v.sourceId)) { seenIds.add(v.sourceId); out.push(v); }",
  "    }",
  "    return true;",
  "  } catch (err) {",
  "    const status = (err as { response?: { status?: number } }).response?.status;",
  "    if (status === 403) {",
  '      logger.error("[HH] 403 Forbidden — токен невалиден. Обнови HH_API_TOKEN в .env");',
  "      return false;",
  "    }",
  '    logger.error("[HH] Ошибка " + cat + "/" + country + " \\"" + query + "\\": " + String(err));',
  "    return true;",
  "  }",
  "}",
  "",
  "async function scrapeCountry(country: Country, areaId: string, headers: Record<string, string>): Promise<ParsedVacancy[]> {",
  "  const all: ParsedVacancy[] = [];",
  "  const seenIds = new Set<string>();",
  "  let aborted = false;",
  "  for (const [cat, queries] of Object.entries(SEARCH_QUERIES) as [JobCategory, string[]][]) {",
  "    for (const query of queries) {",
  "      if (aborted) break;",
  "      const ok = await scrapeQuery(query, cat, country, areaId, headers, seenIds, all);",
  "      if (!ok) { aborted = true; break; }",
  "      await sleep(config.bot.requestDelayMs);",
  "    }",
  "  }",
  "  return all;",
  "}",
  "",
  "// --- Source ---",
  "",
  "export const hhSource: Source = {",
  '  name: "hh.ru",',
  '  countries: ["BY", "RU", "GE", "AM", "KZ"],',
  "  async scrape(country: Country): Promise<ParsedVacancy[]> {",
  "    const token = await getAccessToken();",
  "    if (!token) {",
  '      logger.warn("[HH] Нет токена! Задай HH_API_TOKEN или HH_CLIENT_ID + HH_CLIENT_SECRET в .env");',
  "      return [];",
  "    }",
  "    return scrapeCountry(country, COUNTRY_AREA[country], {",
  '      "User-Agent": "VacanciesBot/1.0",',
  '      Authorization: "Bearer " + token,',
  "    });",
  "  },",
  "};",
];

fs.writeFileSync("src/sources/hh.ts", lines.join("\n"), "utf8");
console.log("Written", lines.length, "lines to src/sources/hh.ts");
